name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * 1-5'
  repository_dispatch:
    types: [ run_e2e_tests ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        TEST_USER_USERNAME: ${{ secrets.TEST_USER_USERNAME }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Send Discord notification
      if: failure()
      env:
        DISCORD_JAQPOT_ALERTS_WEBHOOK: ${{ secrets.DISCORD_JAQPOT_ALERTS_WEBHOOK }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub Actions",
        "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
        "content": "End-to-end tests failed! Check the report for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }' $DISCORD_JAQPOT_ALERTS_WEBHOOK
    - name: Upload report to Discord
      if: failure()
      env:
        DISCORD_JAQPOT_ALERTS_WEBHOOK: ${{ secrets.DISCORD_JAQPOT_ALERTS_WEBHOOK }}
      run: |
        curl -H "Content-Type: multipart/form-data" -X POST -F "file=@playwright-report/index.html" $DISCORD_JAQPOT_ALERTS_WEBHOOK
